# Generated by Django 5.0.7 on 2024-07-23 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_logincontent_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logincontent",
            name="pub_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
