# Generated by Django 5.0.7 on 2024-07-19 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postDetail", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PostContent",
            new_name="MainContent",
        ),
    ]
