# Generated by Django 5.0.7 on 2024-07-19 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postDetail", "0002_rename_postcontent_maincontent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MainContent",
            new_name="PostContent",
        ),
    ]
