# Generated by Django 5.0.7 on 2024-07-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postDetail", "0003_rename_maincontent_postcontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcontent",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
